pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ayushheheheha/agile_assessment_7.git'
            }
        }

        stage('Generate Report') {
            steps {
                dir('project1-archive') {
                    bat 'python app.py'
                }
            }
        }

        stage('Archive Report') {
            steps {
                archiveArtifacts artifacts: 'project1-archive/evaluation_report.txt', fingerprint: true
            }
        }
    }
}