pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ayushheheheha/agile_assessment_7.git'
            }
        }

        stage('Parallel Checks') {
            parallel {
                stage('Exam Portal Check') {
                    steps {
                        dir('project2-parallel') {
                            bat 'python portal_check.py'
                        }
                    }
                }
                stage('Evaluation Engine Check') {
                    steps {
                        dir('project2-parallel') {
                            bat 'python evaluation_check.py'
                        }
                    }
                }
            }
        }

        stage('Summary') {
            steps {
                echo 'Both frontend and backend checks are complete.'
            }
        }
    }
}